"""
Convert a small PyTorch vision model (ResNet18) to Core ML with ANE eligibility,
then run a single inference through the Core ML runtime on macOS.

Expected runtime: ~30s on first run (includes a torchvision weight download).

Notes:
- compute_units=ct.ComputeUnit.CPU_AND_NE marks ops eligible for ANE.
  The Core ML compiler still decides per-op. Open the .mlpackage in Xcode
  > Performance to see the actual dispatch.
- minimum_deployment_target=ct.target.iOS18 enables modern features
  (MLState, palettization) even though we don't use them here.
"""
import numpy as np
import torch
import torchvision.models as models
import coremltools as ct


def main() -> None:
    model = models.resnet18(weights=models.ResNet18_Weights.DEFAULT).eval()
    example = torch.randn(1, 3, 224, 224)

    print("Tracing model...")
    traced = torch.jit.trace(model, example)

    print("Converting to Core ML (compute_units = CPU_AND_NE)...")
    mlmodel = ct.convert(
        traced,
        inputs=[ct.TensorType(name="input", shape=example.shape)],
        compute_units=ct.ComputeUnit.CPU_AND_NE,
        minimum_deployment_target=ct.target.iOS18,
        convert_to="mlprogram",
    )
    mlmodel.save("ResNet18.mlpackage")
    print("Saved ResNet18.mlpackage")

    # Run inference via the Core ML runtime (macOS only).
    pred = mlmodel.predict({"input": example.numpy().astype(np.float32)})
    # The output blob name is generated by the converter; grab the first array.
    out = next(v for v in pred.values() if isinstance(v, np.ndarray))
    top5 = np.argsort(-out.squeeze())[:5].tolist()
    print(f"Core ML output top-5 indices: {top5}")


if __name__ == "__main__":
    main()
